name: Deploy 
on:
  push:
    
jobs: 
    deploy: 
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Replace environment variables
          run: |
            sed -i "s/REPLACE_WITH_SUPABASE_ANON_KEY/${{ secrets.SUPABASE_ANON_KEY }}/g" src/environments/environment.prod.ts
            sed -i "s#REPLACE_WITH_SUPABASE_URL#${{ secrets.SUPABASE_URL }}#g" src/environments/environment.prod.ts
    
        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '20'

        - name: Install dependencies
          run: | 
            npm install

        - name: Build
          run: | 
            npm run build --configuration=production

        - name: Log files
          run: | 
            ls -la
            cd ./dist
            ls -la

        - name: 📂 Upload
          uses: SamKirkland/FTP-Deploy-Action@v4.3.4
          with:
            server: gfram1027.siteground.biz
            username: github@demo.marginleft.at
            password: ${{ secrets.ftp_password }}
            dry-run: false
            local-dir: ./dist/master-thesis-protoype/
            server-dir: /demo.marginleft.at/public_html/